import "./hoho.jpg";

const data = [
  {
    prodct_num: 1,
    product_writer: "우리술방",
    product_datetime: "2023.02.28",
    product_mainimage: "./hoho.jpg",
    product_name: "호호1",
    product_introduction: "안녕하세요. 탁주입니다.",
    product_category: "탁주",
    product_percentage: "12.50",
    product_volume: 375,
    product_price: 15000,
    product_stock: 30,
  },
  {
    prodct_num: 2,
    product_writer: "우리술방",
    product_datetime: "2023.02.28",
    product_mainimage: "./hoho.jpg",
    product_name: "호호2",
    product_introduction: "안녕하세요. 탁주입니다.",
    product_category: "탁주",
    product_percentage: "12.50",
    product_volume: 375,
    product_price: 15000,
    product_stock: 30,
  },
  {
    prodct_num: 3,
    product_writer: "우리술방",
    product_datetime: "2023.02.28",
    product_mainimage: "./hoho.jpg",
    product_name: "호호3",
    product_introduction: "안녕하세요. 과실주입니다.",
    product_category: "과실주",
    product_percentage: "12.50",
    product_volume: 375,
    product_price: 15000,
    product_stock: 30,
  },
  {
    prodct_num: 4,
    product_writer: "우리술방",
    product_datetime: "2023.02.28",
    product_mainimage: "./hoho.jpg",
    product_name: "호호4",
    product_introduction: "안녕하세요. 증류주입니다.",
    product_category: "증류주",
    product_percentage: "12.50",
    product_volume: 375,
    product_price: 15000,
    product_stock: 30,
  },
];

export default data;
